"""empty message

Revision ID: b06dcc380443
Revises: 48b9d030af88
Create Date: 2021-01-14 16:20:56.752547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06dcc380443'
down_revision = '48b9d030af88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))

    # ### update the completed column values for already existing data
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL')

    # ### change
    op.alter_column('todo','completed',nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
